config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'signups#new', as: :signup
  post '/signup', to: 'signups#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/'), via: 'get'
  get '/login', to: redirect('/auth/twitter'), as: :login
  get '/logout', to: 'sessions#destroy'

  resource :address, only: %i[show edit update]

  root to: 'christmases#show'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :santa

  %i[name line_1 line_2 suburb postcode city country].each do |attr|
    attr_encrypted attr, key: ENV['ENCRYPTION_KEY'], allow_empty_value: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :santa
  has_one :user, through: :santa

  validates :uid, uniqueness: { scope: :santa_id }

  def self.mutual
    includes(:santa, :user)
      .references(:santa, :user)
      .joins(
        <<-SQL
          INNER JOIN candidates c2 ON c2.uid = users.uid
          INNER JOIN santas s2 ON c2.santa_id = s2.id
          INNER JOIN users u2 ON s2.user_id = u2.id
        SQL
      )
      .where('u2.uid = candidates.uid')
  end
end

app/models/christmas.rb
class Christmas < ApplicationRecord
  has_many :santas

  validates :signup_deadline, presence: true

  scope :current, -> { where('signup_deadline >= ? AND signup_deadline < ?', Time.now.beginning_of_year, Time.now.beginning_of_year + 1.year) }
  scope :oldest_first, -> { order(signup_deadline: :asc) }

  def self.present
    current.first
  end

  def assignment_date
    signup_deadline.to_date + 6.days
  end
end

app/models/santa.rb
class Santa < ApplicationRecord
  belongs_to :christmas
  belongs_to :user
  belongs_to :recipient, class_name: 'Santa', optional: true
  has_many :candidates, dependent: :destroy, autosave: true
  has_one :address

  validates :christmas_id, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :christmas_id }
  validates :recipient_id, uniqueness: { scope: :christmas_id }, allow_nil: true
  validates :conditions, acceptance: true, if: :new_record?
  validate :at_least_three_candidates

  delegate :name, :uid, to: :user

  private

  def at_least_three_candidates
    errors.add(:mutuals, 'You need at least 3 people on your ‘nice’ list') \
      unless candidates.size >= 3
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :santas, dependent: :destroy

  validates :name, :avatar, presence: true
  validates :screen_name, :uid,
    presence: true,
    uniqueness: { case_sensitive: false }

  def to_param
    username
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :santa_required

  def show
  end

  def edit
  end

  def update
    address.update!(address_params)
    redirect_to address_path
  end

  private

  def address
    @address ||= santa.address || santa.build_address
  end

  def address_params
    params.require(:address).permit(:name, :line_1, :line_2, :suburb, :postcode, :city, :country)
  end

  helper_method :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(uid: session[:current_user])
  end

  def current_user=(user)
    if user.present?
      session[:current_user] = user.uid
    else
      session.delete(:current_user)
    end
  end

  def logged_in?
    current_user.present?
  end

  def christmas
    @christmas ||= Christmas.present
  end

  def santa
    christmas&.santas&.where(user_id: current_user&.id)&.first
  end

  def login_required
    redirect_to root_path, alert: 'Please log in first!' unless logged_in?
  end

  def santa_required
    redirect_to root_path, alert: 'Please log in first!' unless santa.present?
  end

  helper_method :logged_in?, :current_user, :christmas, :santa
end

app/controllers/christmases_controller.rb
class ChristmasesController < ApplicationController
  def show; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    self.current_user = UserFromOauth.new(auth_hash).user
    redirect_to root_path
  end

  def destroy
    self.current_user = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :login_required

  def new
    redirect_to root_path, notice: 'You’re already signed up!' if santa
  end

  def create
    signup.attributes = signup_params
    if signup.save
      redirect_to root_path, notice: 'You’re all signed up!'
    else
      render :new
    end
  end

  private

  def signup
    @signup ||= SignupForm.new(user: current_user, christmas: christmas)
  end

  def signup_params
    params.require(:signup).permit(:conditions, candidate_uids: [])
  end

  helper_method :signup
end

app/helpers/address_helper.rb
module AddressHelper
  def format_address(address)
    content_tag :address do
      concat content_tag(:div, address.name) if address.name?
      concat content_tag(:div, address.line_1) if address.line_1?
      concat content_tag(:div, address.line_2) if address.line_2?
      concat content_tag(:div, address.suburb) if address.suburb?
      concat content_tag(:div, [address.city, address.postcode].join(', ')) if address.city? || address.postcode?
      concat content_tag(:div, address.country.upcase) if address.country?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_address.html.haml
= format_address(address)

app/views/addresses/_form.html.haml
%ul
  %li Make sure you will be able to receive parcels to this address during December.
  %li The only person who will see your address is your Santa.
  %li Addresses are stored encrypted in the database

= form_for address, url: address_path, method: :put do |form|
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .row
    .col-md
      .form-group
        = form.label :line_1
        = form.text_field :line_1, class: 'form-control'
    .col-md
      .form-group
        = form.label :line_2
        = form.text_field :line_2, class: 'form-control'
  .row
    .col-md
      .form-group
        = form.label :suburb
        = form.text_field :suburb, class: 'form-control'
    .col-md
      .form-group
        = form.label :postcode
        = form.text_field :postcode, class: 'form-control'
  .row
    .col-md
      .form-group
        = form.label :city
        = form.text_field :city, class: 'form-control'
    .col-md
      .form-group
        = form.label :country
        = form.text_field :country, class: 'form-control'

  = form.submit 'Save address', class: 'btn btn-primary'

app/views/addresses/edit.html.haml
%h1 Edit your address
= render 'form'

app/views/addresses/show.html.haml
- if address.persisted?
  %h1 Your address
  %p We have your address recorded as:
  %blockquote= render address
  %p Make sure you will be able to receive parcels to this address during December.
  = link_to 'Change my address', edit_address_path, class: 'btn btn-outline-primary'
- else
  %h1 Please enter your address
  = render 'form'

app/views/christmases/_home.html.haml
%section.how-it-works
  %h1 Hold me closer, Tiny Santa…
  %p
    = pluralize christmas.santas.count, 'Santa'
    signed up so far.

  = render partial: 'recipient', object: santa&.recipient

  .row.align-items-stretch
    .step.col-md-6.col-lg-3
      %section
        %h3 Sign up
        %p
          Confirm your details and curate your naughty/nice list by
          = succeed '.' do
            = l(christmas.signup_deadline.to_date - 1, format: :short)
        - if logged_in?
          - if santa.present?
            = link_to "#{santa.address ? 'Edit' : 'Add'} your address", address_path, class: 'btn btn-outline-primary'
          - elsif christmas.signup_deadline.to_date <= Date.today
            %button.btn.btn-outline-primary{disabled: true} Signups closed
          - else
            = link_to 'Get started', signup_path, class: 'btn btn-primary btn-block'
        - else
          = link_to 'Log in with Twitter', login_path, class: 'btn btn-primary'
    .step.col-md-6.col-lg-3
      %section
        %h3 Get your giftee
        %p A robot uses a special algorithm to choose one of your LT mutuals for you to buy a gift for.
        %button.btn.btn-outline-primary{disabled: true}
          - if christmas.assignment_date.past?
            Done!
          - else
            Coming by
            = l(christmas.assignment_date, format: :short)
    .step.col-md-6.col-lg-3
      %section
        %h3 Send a gift
        %p There aren’t any warehouses or anything. Just send it straight there.
    .step.col-md-6.col-lg-3
      %section
        %h3 Get a gift!
        %p A present turns up in the post. Tweet excitedly about it (on LT, of course).

%section.faq
  %h3 Who's responsible?
  %p
    = link_to '@privatecoley', 'http://twitter.com/privatecoley'
    had the idea.
    = link_to '@extrapylons', 'http://twitter.com/extrapylons'
    wrote the code.

  %h3 Who can play?
  %p
    We all have locked accounts and different follower lists.
    The idea is that anyone can sign up and your Santa
    and your giftee will both be chosen from among your
    LT mutuals, so you WILL know each other.
    This gets a bit tricky to manage,
    but we think we have it sorted.

  %h3 Concerned about privacy?
  %p Us too. Your address won’t be shared with anyone except your Santa. We’re also considering ways to encrypt it in the database so that we can’t even see it.

app/views/christmases/_missing.html.haml
.jumbotron
  %h1 There’s no such thing as Christmas.
  %p We probably just haven’t set things up for this year.

app/views/christmases/_recipient.html.haml
- if recipient.present?
  .jumbotron
    %p You are Tiny Santa for
    %h1= link_to '@' + recipient.user.screen_name, "https://twitter.com/#{recipient.user.screen_name}"

    %hr

    - if recipient.address
      %input#show-address{type: 'checkbox'}
      %label{for: 'show-address'}
        %span.hiding Show address
        %span.showing Hide address

      .address
        %blockquote.blockquote= format_address(recipient.address)
        %p.small
          Please respect our community by not storing or sharing this address
          or leaving it open where other people can see it.
    - else
      %p They haven’t entered their address yet. Check back later!

app/views/christmases/_signup.html.haml
%section.how-it-works
  %h1 Hold me closer, Tiny Santa…

  .row.align-items-stretch
    .step.col-md-6.col-lg-3
      %section
        %h3 Sign up
        %p
          Confirm your details and curate your naughty/nice list by
          = succeed '.' do
            = l(christmas.signup_deadline.to_date - 1, format: :short)
        = link_to 'Get started', '#', class: 'btn btn-primary btn-block'
    .step.col-md-6.col-lg-3
      %section
        %h3 Get your giftee
        %p A robot uses a special algorithm to choose one of your LT mutuals for you to buy a gift for.
    .step.col-md-6.col-lg-3
      %section
        %h3 Send a gift
        %p There aren’t any warehouses or anything. Just send it straight there.
    .step.col-md-6.col-lg-3
      %section
        %h3 Get a gift!
        %p A present turns up in the post. Tweet excitedly about it (on LT, of course).

%section.faq
  %h3 Who's responsible?
  %p
    = link_to '@privatecoley', 'http://twitter.com/privatecoley'
    had the idea.
    = link_to '@extrapylons', 'http://twitter.com/extrapylons'
    wrote the code.

  %h3 Who can play?
  %p
    We all have locked accounts and different follower lists.
    The idea is that anyone can sign up and your Santa
    and your giftee will both be chosen from among your
    LT mutuals, so you WILL know each other.
    This gets a bit tricky to manage,
    but we think we have it sorted.

  %h3 Concerned about privacy?
  %p Us too. Your address won’t be shared with anyone except your Santa. We’re also considering ways to encrypt it in the database so that we can’t even see it.

app/views/christmases/show.html.haml
- if christmas.present?
  = render 'home'
- else
  = render 'missing'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title Tiny Santa
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navbar'
    .container
      - flash.each do |key, message|
        .alert{class: "alert-#{{notice: :info, alert: :warning}[key.to_sym] || key}"}= message
      = yield

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-dark.navbar-expand-lg.fixed-top
  = link_to 'Tiny Santa', root_path, class: 'navbar-brand'
  %button.navbar-toggler{'aria-controls' => 'navigation', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation', 'data-target' => '#navigation', 'data-toggle' => 'collapse', :type => 'button'}
    %span.navbar-toggler-icon
  #navigation.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto
      - if logged_in?
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle#user-menu{'href' => '#', 'role' => 'button', 'data-toggle' => 'dropdown', 'aria-haspopup' => true, 'aria-expanded' => false}
            = image_tag current_user.avatar
            = current_user.screen_name
          .dropdown-menu{'aria-labelledby' => 'user-menu'}
            = link_to 'Log out', logout_path, class: 'dropdown-item'
      - else
        %li.nav-item
          = link_to 'Log in', login_path, class: 'btn btn-outline-light'

app/views/signups/_candidate.html.haml
%li
  %label.custom-control.custom-checkbox.d-flex.align-items-center
    = check_box_tag 'signup[candidate_uids][]', candidate.uid, signup.candidate_uids.include?(candidate.uid), class: 'custom-control-input'
    = image_tag candidate.avatar, alt: candidate.name
    %svg{width: 40, height: 40, viewbox: '0 0 40 40'}
      %path{d: 'M10 10 L30 30 M30 10 L10 30'}
    %span.name
      %b= candidate.screen_name
      %small= candidate.name
    %span.custom-control-indicator

app/views/signups/new.html.haml
= form_for signup, as: :signup, url: signup_path, html: { class: 'signup-form' } do |form|
  - if signup.errors.any?
    .alert.alert-danger
      %h4 Uh-oh, some problems happened?
      %p.mb-0 Check the details below and try again.
  .form-group
    %h4 Your naughty/nice list
    %p
      Deselect anyone you
      %em don’t
      want to be a Tiny Santa for
      (e.g. people you’d normally buy a present for,
      or your main account).
      They won’t see that you’ve done this:
      you’ll only be matched if you both agree.
    - (signup.errors[:mutuals] || []).each do |error|
      .alert.alert-danger= error
    .mutuals
      %ul
        = render partial: 'candidate', collection: signup.mutuals, locals: { form: form, signup: signup }
  %h4 The fine print
  %p
    I acknowledge that I’ll be assigned one of the above
    people as my Tiny Santa gift recipient.
    I definitely promise to buy them something nice
    and send it to them in a timely fashion.
    I understand that one of the above people will
    see my postal address at some point.
  - signup.errors.full_messages_for(:conditions).each do |error|
    .alert.alert-danger= error
  .form-check
    = form.label :conditions do
      = form.check_box :conditions
      Sounds good to me!

  = form.submit 'Sign me up!', class: 'btn btn-primary'

app/views/users/_user.html.haml
.user
  %span.avatar= image_tag user.avatar, alt: user.name
  %span.username= "@#{user.screen_name}"
  %span.name= user.name